### ISSUE TITLE
Cursor is always going to the end of line when using rails console in vimshell

### ISSUE THREAD

**Issue by shubhamgupta731** [Shougo/vimshell.vim#204]
After typing a few words in the console which is open inside vimshell if I want to go the beginning of the word my cursor is automatically being placed at the end of the line. I disabled all plugins before testing this. 

Here is a screen cast:

http://quick.as/kD6YiOxqp

**Comment by shubhamgupta731** [comment]
Its even happening in python!!!

**Comment by Shougo** [comment]
I don't know the detailed feature.
Please upload the commands to test it.

**Comment by supermomonga** [comment]
Maybe you should use `:VimShellInteractive`, like `:VimShellInteractive rails c`.

**Comment by shubhamgupta731** [comment]
It works as it should with VimShellInteractive but not with VimShell. I have just started using this plugin. So basically if I want to run ruby consoles or python consoles I have to use VimShellInteractive?

**Comment by shubhamgupta731** [comment]
@Shougo as you can see in the screen cast I am not doing anything special. When I am on the active line of the interactive shell, be it ruby or python, it always takes me to the end of the line even if I want to go to any character within the active line in the console. However, this is only true for the last line in the shell. I can go to any character above the last line without any issue. But I am not encountering this issue with VimShellInteractive rails c.

**Comment by Shougo** [comment]
@shubhamgupta731 Please describe the instructions.  I will try it.

For example:

1. `:VimShell`
2. put `irb`

Note: I don't have rails environment.  Other commands are better.

**Comment by shubhamgupta731** [comment]
Sure...

1. `:VimShell`
2. put `irb`
3. write `puts "hello world"`. Don't press enter
4. Try to take your cursor to `hello` or `puts` in normal mode.

**Comment by Shougo** [comment]
Fixed.

**Comment by shubhamgupta731** [comment]
I pulled your latest version but it is still not fixed... :cry:

**Comment by shubhamgupta731** [comment]
So I do 

1. :VimShell
2. irb
3. `puts "hello world"` don't press enter
4. Go into Normal mode by pressing `Esc`
5. Try to take the cursor to `puts` or `hello`.

**Comment by Shougo** [comment]
Fixed.  It is another problem.
